/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Paths {
  "/getOnboardingUrl": {
    post: {
      request: {
        path?: {};
        headers?: {
          "Content-Type"?: "application/json";
          [k: string]: unknown;
        };
        cookies?: {
          [k: string]: unknown;
        };
        query?: {
          [k: string]: unknown;
        };
        body?: {
          /**
           * The account holder code you provided when you created the account holder.
           */
          accountHolderCode: string;
          collectInformation?: {
            /**
             * Indicates whether [bank account details](https://docs.adyen.com/marketplaces-and-platforms/classic/verification-checks/bank-account-check) must be collected. Default is **true**.
             */
            bankDetails?: boolean;
            /**
             * Indicates whether [business details](https://docs.adyen.com/marketplaces-and-platforms/classic/verification-checks/company-check) must be collected. Default is **true**.
             */
            businessDetails?: boolean;
            /**
             * Indicates whether [individual details](https://docs.adyen.com/marketplaces-and-platforms/classic/verification-checks/identity-check) must be collected. Default is **true**.
             */
            individualDetails?: boolean;
            /**
             * Indicates whether [legal arrangement details](https://docs.adyen.com/marketplaces-and-platforms/classic/verification-checks/legal-arrangements) must be collected. Default is **true**.
             */
            legalArrangementDetails?: boolean;
            /**
             * Indicates whether answers to a [PCI questionnaire](https://docs.adyen.com/marketplaces-and-platforms/classic/platforms-for-partners#onboard-partner-platform) must be collected. Applies only to partner platforms. Default is **true**.
             */
            pciQuestionnaire?: boolean;
            /**
             * Indicates whether [shareholder details](https://docs.adyen.com/marketplaces-and-platforms/classic/verification-checks/identity-check) must be collected. Defaults to **true**.
             */
            shareholderDetails?: boolean;
            [k: string]: unknown;
          };
          /**
           * Indicates if editing checks is allowed even if all the checks have passed.
           */
          editMode?: boolean;
          /**
           * The URL to which the account holder is redirected after completing an OAuth authentication with a bank through Trustly/PayMyBank.
           */
          mobileOAuthCallbackUrl?: string;
          /**
           * The platform name which will show up in the welcome page.
           */
          platformName?: string;
          /**
           * The URL where the account holder will be redirected back to after they complete the onboarding, or if their session times out. Maximum length of 500 characters. If you don't provide this, the account holder will be redirected back to the default return URL configured in your platform account.
           */
          returnUrl?: string;
          /**
           * The language to be used in the page, specified by a combination of a language and country code. For example, **pt-BR**.
           *
           * If not specified in the request or if the language is not supported, the page uses the browser language. If the browser language is not supported, the page uses **en-US** by default.
           *
           * For a list of supported languages, refer to [Change the page language](https://docs.adyen.com/marketplaces-and-platforms/classic/hosted-onboarding-page/customize-experience#change-page-language).
           */
          shopperLocale?: string;
          showPages?: {
            /**
             * Indicates whether the page with bank account details must be shown. Defaults to **true**.
             */
            bankDetailsSummaryPage?: boolean;
            /**
             * Indicates whether the bank check instant verification' details must be shown. Defaults to **true**.
             */
            bankVerificationPage?: boolean;
            /**
             * Indicates whether the page with the company's or organization's details must be shown. Defaults to **true**.
             */
            businessDetailsSummaryPage?: boolean;
            /**
             * Indicates whether the checks overview page must be shown. Defaults to **false**.
             */
            checksOverviewPage?: boolean;
            /**
             * Indicates whether the page with the individual's details must be shown. Defaults to **true**.
             */
            individualDetailsSummaryPage?: boolean;
            /**
             * Indicates whether the page with the legal arrangements' details must be shown. Defaults to **true**.
             */
            legalArrangementsDetailsSummaryPage?: boolean;
            /**
             * Indicates whether the page to manually add bank account' details must be shown. Defaults to **true**.
             */
            manualBankAccountPage?: boolean;
            /**
             * Indicates whether the page with the shareholders' details must be shown. Defaults to **true**.
             */
            shareholderDetailsSummaryPage?: boolean;
            /**
             * Indicates whether the welcome page must be shown. Defaults to **false**.
             */
            welcomePage?: boolean;
            [k: string]: unknown;
          };
          [k: string]: unknown;
        };
      };
      responses:
        | {
            status: "200";
            headers: {
              "Content-Type": "application/json";
              [k: string]: unknown;
            };
            body: {
              /**
               * Information about any invalid fields.
               */
              invalidFields?: {
                /**
                 * The validation error code.
                 */
                errorCode?: number;
                /**
                 * A description of the validation error.
                 */
                errorDescription?: string;
                fieldType?: {
                  /**
                   * The full name of the property.
                   */
                  field?: string;
                  /**
                   * The type of the field.
                   */
                  fieldName?:
                    | "accountCode"
                    | "accountHolderCode"
                    | "accountHolderDetails"
                    | "accountNumber"
                    | "accountStateType"
                    | "accountStatus"
                    | "accountType"
                    | "address"
                    | "balanceAccount"
                    | "balanceAccountActive"
                    | "balanceAccountCode"
                    | "balanceAccountId"
                    | "bankAccount"
                    | "bankAccountCode"
                    | "bankAccountName"
                    | "bankAccountUUID"
                    | "bankBicSwift"
                    | "bankCity"
                    | "bankCode"
                    | "bankName"
                    | "bankStatement"
                    | "branchCode"
                    | "businessContact"
                    | "cardToken"
                    | "checkCode"
                    | "city"
                    | "companyRegistration"
                    | "constitutionalDocument"
                    | "controller"
                    | "country"
                    | "countryCode"
                    | "currency"
                    | "currencyCode"
                    | "dateOfBirth"
                    | "description"
                    | "destinationAccountCode"
                    | "document"
                    | "documentContent"
                    | "documentExpirationDate"
                    | "documentIssuerCountry"
                    | "documentIssuerState"
                    | "documentName"
                    | "documentNumber"
                    | "documentType"
                    | "doingBusinessAs"
                    | "drivingLicence"
                    | "drivingLicenceBack"
                    | "drivingLicenceFront"
                    | "drivingLicense"
                    | "email"
                    | "firstName"
                    | "formType"
                    | "fullPhoneNumber"
                    | "gender"
                    | "hopWebserviceUser"
                    | "houseNumberOrName"
                    | "iban"
                    | "idCard"
                    | "idCardBack"
                    | "idCardFront"
                    | "idNumber"
                    | "identityDocument"
                    | "individualDetails"
                    | "infix"
                    | "jobTitle"
                    | "lastName"
                    | "lastReviewDate"
                    | "legalArrangement"
                    | "legalArrangementCode"
                    | "legalArrangementEntity"
                    | "legalArrangementEntityCode"
                    | "legalArrangementLegalForm"
                    | "legalArrangementMember"
                    | "legalArrangementMembers"
                    | "legalArrangementName"
                    | "legalArrangementReference"
                    | "legalArrangementRegistrationNumber"
                    | "legalArrangementTaxNumber"
                    | "legalArrangementType"
                    | "legalBusinessName"
                    | "legalEntity"
                    | "legalEntityType"
                    | "logo"
                    | "merchantAccount"
                    | "merchantCategoryCode"
                    | "merchantHouseNumber"
                    | "merchantReference"
                    | "microDeposit"
                    | "name"
                    | "nationality"
                    | "originalReference"
                    | "ownerCity"
                    | "ownerCountryCode"
                    | "ownerDateOfBirth"
                    | "ownerHouseNumberOrName"
                    | "ownerName"
                    | "ownerPostalCode"
                    | "ownerState"
                    | "ownerStreet"
                    | "passport"
                    | "passportNumber"
                    | "payoutMethodCode"
                    | "payoutSchedule"
                    | "pciSelfAssessment"
                    | "personalData"
                    | "phoneCountryCode"
                    | "phoneNumber"
                    | "postalCode"
                    | "primaryCurrency"
                    | "reason"
                    | "registrationNumber"
                    | "returnUrl"
                    | "schedule"
                    | "shareholder"
                    | "shareholderCode"
                    | "shareholderCodeAndSignatoryCode"
                    | "shareholderCodeOrSignatoryCode"
                    | "shareholderType"
                    | "shareholderTypes"
                    | "shopperInteraction"
                    | "signatory"
                    | "signatoryCode"
                    | "socialSecurityNumber"
                    | "sourceAccountCode"
                    | "splitAccount"
                    | "splitConfigurationUUID"
                    | "splitCurrency"
                    | "splitValue"
                    | "splits"
                    | "stateOrProvince"
                    | "status"
                    | "stockExchange"
                    | "stockNumber"
                    | "stockTicker"
                    | "store"
                    | "storeDetail"
                    | "storeName"
                    | "storeReference"
                    | "street"
                    | "taxId"
                    | "tier"
                    | "tierNumber"
                    | "transferCode"
                    | "ultimateParentCompany"
                    | "ultimateParentCompanyAddressDetails"
                    | "ultimateParentCompanyAddressDetailsCountry"
                    | "ultimateParentCompanyBusinessDetails"
                    | "ultimateParentCompanyBusinessDetailsLegalBusinessName"
                    | "ultimateParentCompanyBusinessDetailsRegistrationNumber"
                    | "ultimateParentCompanyCode"
                    | "ultimateParentCompanyStockExchange"
                    | "ultimateParentCompanyStockNumber"
                    | "ultimateParentCompanyStockNumberOrStockTicker"
                    | "ultimateParentCompanyStockTicker"
                    | "unknown"
                    | "value"
                    | "verificationType"
                    | "virtualAccount"
                    | "visaNumber"
                    | "webAddress"
                    | "year";
                  /**
                   * The code of the shareholder that the field belongs to. If empty, the field belongs to an account holder.
                   */
                  shareholderCode?: string;
                  [k: string]: unknown;
                };
                [k: string]: unknown;
              }[];
              /**
               * The reference of a request. Can be used to uniquely identify the request.
               */
              pspReference?: string;
              /**
               * The URL to the Hosted Onboarding Page where you should redirect your sub-merchant. This URL must be used within 30 seconds and can only be used once.
               */
              redirectUrl?: string;
              /**
               * The result code.
               */
              resultCode?: string;
              [k: string]: unknown;
            };
          }
        | {
            status: "400";
            headers: {
              "Content-Type": "application/json";
              [k: string]: unknown;
            };
            body: {
              /**
               * The error code mapped to the error message.
               */
              errorCode?: string;
              /**
               * The category of the error.
               */
              errorType?: string;
              /**
               * A short explanation of the issue.
               */
              message?: string;
              /**
               * The PSP reference of the payment.
               */
              pspReference?: string;
              /**
               * The HTTP response status.
               */
              status?: number;
              [k: string]: unknown;
            };
          }
        | {
            status: "401";
            headers: {
              "Content-Type": "application/json";
              [k: string]: unknown;
            };
            body: {
              /**
               * The error code mapped to the error message.
               */
              errorCode?: string;
              /**
               * The category of the error.
               */
              errorType?: string;
              /**
               * A short explanation of the issue.
               */
              message?: string;
              /**
               * The PSP reference of the payment.
               */
              pspReference?: string;
              /**
               * The HTTP response status.
               */
              status?: number;
              [k: string]: unknown;
            };
          }
        | {
            status: "403";
            headers: {
              "Content-Type": "application/json";
              [k: string]: unknown;
            };
            body: {
              /**
               * The error code mapped to the error message.
               */
              errorCode?: string;
              /**
               * The category of the error.
               */
              errorType?: string;
              /**
               * A short explanation of the issue.
               */
              message?: string;
              /**
               * The PSP reference of the payment.
               */
              pspReference?: string;
              /**
               * The HTTP response status.
               */
              status?: number;
              [k: string]: unknown;
            };
          }
        | {
            status: "422";
            headers: {
              "Content-Type": "application/json";
              [k: string]: unknown;
            };
            body: {
              /**
               * The error code mapped to the error message.
               */
              errorCode?: string;
              /**
               * The category of the error.
               */
              errorType?: string;
              /**
               * A short explanation of the issue.
               */
              message?: string;
              /**
               * The PSP reference of the payment.
               */
              pspReference?: string;
              /**
               * The HTTP response status.
               */
              status?: number;
              [k: string]: unknown;
            };
          }
        | {
            status: "500";
            headers: {
              "Content-Type": "application/json";
              [k: string]: unknown;
            };
            body: {
              /**
               * The error code mapped to the error message.
               */
              errorCode?: string;
              /**
               * The category of the error.
               */
              errorType?: string;
              /**
               * A short explanation of the issue.
               */
              message?: string;
              /**
               * The PSP reference of the payment.
               */
              pspReference?: string;
              /**
               * The HTTP response status.
               */
              status?: number;
              [k: string]: unknown;
            };
          };
    };
  };
  "/getPciQuestionnaireUrl": {
    post: {
      request: {
        path?: {};
        headers?: {
          "Content-Type"?: "application/json";
          [k: string]: unknown;
        };
        cookies?: {
          [k: string]: unknown;
        };
        query?: {
          [k: string]: unknown;
        };
        body?: {
          /**
           * The account holder code you provided when you created the account holder.
           */
          accountHolderCode: string;
          /**
           * The URL where the account holder will be redirected back to after they fill out the questionnaire, or if their session times out. Maximum length of 500 characters.
           */
          returnUrl?: string;
          [k: string]: unknown;
        };
      };
      responses:
        | {
            status: "200";
            headers: {
              "Content-Type": "application/json";
              [k: string]: unknown;
            };
            body: {
              /**
               * Information about any invalid fields.
               */
              invalidFields?: {
                /**
                 * The validation error code.
                 */
                errorCode?: number;
                /**
                 * A description of the validation error.
                 */
                errorDescription?: string;
                fieldType?: {
                  /**
                   * The full name of the property.
                   */
                  field?: string;
                  /**
                   * The type of the field.
                   */
                  fieldName?:
                    | "accountCode"
                    | "accountHolderCode"
                    | "accountHolderDetails"
                    | "accountNumber"
                    | "accountStateType"
                    | "accountStatus"
                    | "accountType"
                    | "address"
                    | "balanceAccount"
                    | "balanceAccountActive"
                    | "balanceAccountCode"
                    | "balanceAccountId"
                    | "bankAccount"
                    | "bankAccountCode"
                    | "bankAccountName"
                    | "bankAccountUUID"
                    | "bankBicSwift"
                    | "bankCity"
                    | "bankCode"
                    | "bankName"
                    | "bankStatement"
                    | "branchCode"
                    | "businessContact"
                    | "cardToken"
                    | "checkCode"
                    | "city"
                    | "companyRegistration"
                    | "constitutionalDocument"
                    | "controller"
                    | "country"
                    | "countryCode"
                    | "currency"
                    | "currencyCode"
                    | "dateOfBirth"
                    | "description"
                    | "destinationAccountCode"
                    | "document"
                    | "documentContent"
                    | "documentExpirationDate"
                    | "documentIssuerCountry"
                    | "documentIssuerState"
                    | "documentName"
                    | "documentNumber"
                    | "documentType"
                    | "doingBusinessAs"
                    | "drivingLicence"
                    | "drivingLicenceBack"
                    | "drivingLicenceFront"
                    | "drivingLicense"
                    | "email"
                    | "firstName"
                    | "formType"
                    | "fullPhoneNumber"
                    | "gender"
                    | "hopWebserviceUser"
                    | "houseNumberOrName"
                    | "iban"
                    | "idCard"
                    | "idCardBack"
                    | "idCardFront"
                    | "idNumber"
                    | "identityDocument"
                    | "individualDetails"
                    | "infix"
                    | "jobTitle"
                    | "lastName"
                    | "lastReviewDate"
                    | "legalArrangement"
                    | "legalArrangementCode"
                    | "legalArrangementEntity"
                    | "legalArrangementEntityCode"
                    | "legalArrangementLegalForm"
                    | "legalArrangementMember"
                    | "legalArrangementMembers"
                    | "legalArrangementName"
                    | "legalArrangementReference"
                    | "legalArrangementRegistrationNumber"
                    | "legalArrangementTaxNumber"
                    | "legalArrangementType"
                    | "legalBusinessName"
                    | "legalEntity"
                    | "legalEntityType"
                    | "logo"
                    | "merchantAccount"
                    | "merchantCategoryCode"
                    | "merchantHouseNumber"
                    | "merchantReference"
                    | "microDeposit"
                    | "name"
                    | "nationality"
                    | "originalReference"
                    | "ownerCity"
                    | "ownerCountryCode"
                    | "ownerDateOfBirth"
                    | "ownerHouseNumberOrName"
                    | "ownerName"
                    | "ownerPostalCode"
                    | "ownerState"
                    | "ownerStreet"
                    | "passport"
                    | "passportNumber"
                    | "payoutMethodCode"
                    | "payoutSchedule"
                    | "pciSelfAssessment"
                    | "personalData"
                    | "phoneCountryCode"
                    | "phoneNumber"
                    | "postalCode"
                    | "primaryCurrency"
                    | "reason"
                    | "registrationNumber"
                    | "returnUrl"
                    | "schedule"
                    | "shareholder"
                    | "shareholderCode"
                    | "shareholderCodeAndSignatoryCode"
                    | "shareholderCodeOrSignatoryCode"
                    | "shareholderType"
                    | "shareholderTypes"
                    | "shopperInteraction"
                    | "signatory"
                    | "signatoryCode"
                    | "socialSecurityNumber"
                    | "sourceAccountCode"
                    | "splitAccount"
                    | "splitConfigurationUUID"
                    | "splitCurrency"
                    | "splitValue"
                    | "splits"
                    | "stateOrProvince"
                    | "status"
                    | "stockExchange"
                    | "stockNumber"
                    | "stockTicker"
                    | "store"
                    | "storeDetail"
                    | "storeName"
                    | "storeReference"
                    | "street"
                    | "taxId"
                    | "tier"
                    | "tierNumber"
                    | "transferCode"
                    | "ultimateParentCompany"
                    | "ultimateParentCompanyAddressDetails"
                    | "ultimateParentCompanyAddressDetailsCountry"
                    | "ultimateParentCompanyBusinessDetails"
                    | "ultimateParentCompanyBusinessDetailsLegalBusinessName"
                    | "ultimateParentCompanyBusinessDetailsRegistrationNumber"
                    | "ultimateParentCompanyCode"
                    | "ultimateParentCompanyStockExchange"
                    | "ultimateParentCompanyStockNumber"
                    | "ultimateParentCompanyStockNumberOrStockTicker"
                    | "ultimateParentCompanyStockTicker"
                    | "unknown"
                    | "value"
                    | "verificationType"
                    | "virtualAccount"
                    | "visaNumber"
                    | "webAddress"
                    | "year";
                  /**
                   * The code of the shareholder that the field belongs to. If empty, the field belongs to an account holder.
                   */
                  shareholderCode?: string;
                  [k: string]: unknown;
                };
                [k: string]: unknown;
              }[];
              /**
               * The reference of a request. Can be used to uniquely identify the request.
               */
              pspReference?: string;
              /**
               * The URL to the PCI compliance questionnaire where you should redirect your account holder. This URL must be used within 30 seconds and can only be used once.
               */
              redirectUrl?: string;
              /**
               * The result code.
               */
              resultCode?: string;
              [k: string]: unknown;
            };
          }
        | {
            status: "400";
            headers: {
              "Content-Type": "application/json";
              [k: string]: unknown;
            };
            body: {
              /**
               * The error code mapped to the error message.
               */
              errorCode?: string;
              /**
               * The category of the error.
               */
              errorType?: string;
              /**
               * A short explanation of the issue.
               */
              message?: string;
              /**
               * The PSP reference of the payment.
               */
              pspReference?: string;
              /**
               * The HTTP response status.
               */
              status?: number;
              [k: string]: unknown;
            };
          }
        | {
            status: "401";
            headers: {
              "Content-Type": "application/json";
              [k: string]: unknown;
            };
            body: {
              /**
               * The error code mapped to the error message.
               */
              errorCode?: string;
              /**
               * The category of the error.
               */
              errorType?: string;
              /**
               * A short explanation of the issue.
               */
              message?: string;
              /**
               * The PSP reference of the payment.
               */
              pspReference?: string;
              /**
               * The HTTP response status.
               */
              status?: number;
              [k: string]: unknown;
            };
          }
        | {
            status: "403";
            headers: {
              "Content-Type": "application/json";
              [k: string]: unknown;
            };
            body: {
              /**
               * The error code mapped to the error message.
               */
              errorCode?: string;
              /**
               * The category of the error.
               */
              errorType?: string;
              /**
               * A short explanation of the issue.
               */
              message?: string;
              /**
               * The PSP reference of the payment.
               */
              pspReference?: string;
              /**
               * The HTTP response status.
               */
              status?: number;
              [k: string]: unknown;
            };
          }
        | {
            status: "422";
            headers: {
              "Content-Type": "application/json";
              [k: string]: unknown;
            };
            body: {
              /**
               * The error code mapped to the error message.
               */
              errorCode?: string;
              /**
               * The category of the error.
               */
              errorType?: string;
              /**
               * A short explanation of the issue.
               */
              message?: string;
              /**
               * The PSP reference of the payment.
               */
              pspReference?: string;
              /**
               * The HTTP response status.
               */
              status?: number;
              [k: string]: unknown;
            };
          }
        | {
            status: "500";
            headers: {
              "Content-Type": "application/json";
              [k: string]: unknown;
            };
            body: {
              /**
               * The error code mapped to the error message.
               */
              errorCode?: string;
              /**
               * The category of the error.
               */
              errorType?: string;
              /**
               * A short explanation of the issue.
               */
              message?: string;
              /**
               * The PSP reference of the payment.
               */
              pspReference?: string;
              /**
               * The HTTP response status.
               */
              status?: number;
              [k: string]: unknown;
            };
          };
    };
  };
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Webhooks {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Components {
  schemas: {
    CollectInformation: {
      /**
       * Indicates whether [bank account details](https://docs.adyen.com/marketplaces-and-platforms/classic/verification-checks/bank-account-check) must be collected. Default is **true**.
       */
      bankDetails?: boolean;
      /**
       * Indicates whether [business details](https://docs.adyen.com/marketplaces-and-platforms/classic/verification-checks/company-check) must be collected. Default is **true**.
       */
      businessDetails?: boolean;
      /**
       * Indicates whether [individual details](https://docs.adyen.com/marketplaces-and-platforms/classic/verification-checks/identity-check) must be collected. Default is **true**.
       */
      individualDetails?: boolean;
      /**
       * Indicates whether [legal arrangement details](https://docs.adyen.com/marketplaces-and-platforms/classic/verification-checks/legal-arrangements) must be collected. Default is **true**.
       */
      legalArrangementDetails?: boolean;
      /**
       * Indicates whether answers to a [PCI questionnaire](https://docs.adyen.com/marketplaces-and-platforms/classic/platforms-for-partners#onboard-partner-platform) must be collected. Applies only to partner platforms. Default is **true**.
       */
      pciQuestionnaire?: boolean;
      /**
       * Indicates whether [shareholder details](https://docs.adyen.com/marketplaces-and-platforms/classic/verification-checks/identity-check) must be collected. Defaults to **true**.
       */
      shareholderDetails?: boolean;
      [k: string]: unknown;
    };
    ErrorFieldType: {
      /**
       * The validation error code.
       */
      errorCode?: number;
      /**
       * A description of the validation error.
       */
      errorDescription?: string;
      fieldType?: {
        /**
         * The full name of the property.
         */
        field?: string;
        /**
         * The type of the field.
         */
        fieldName?:
          | "accountCode"
          | "accountHolderCode"
          | "accountHolderDetails"
          | "accountNumber"
          | "accountStateType"
          | "accountStatus"
          | "accountType"
          | "address"
          | "balanceAccount"
          | "balanceAccountActive"
          | "balanceAccountCode"
          | "balanceAccountId"
          | "bankAccount"
          | "bankAccountCode"
          | "bankAccountName"
          | "bankAccountUUID"
          | "bankBicSwift"
          | "bankCity"
          | "bankCode"
          | "bankName"
          | "bankStatement"
          | "branchCode"
          | "businessContact"
          | "cardToken"
          | "checkCode"
          | "city"
          | "companyRegistration"
          | "constitutionalDocument"
          | "controller"
          | "country"
          | "countryCode"
          | "currency"
          | "currencyCode"
          | "dateOfBirth"
          | "description"
          | "destinationAccountCode"
          | "document"
          | "documentContent"
          | "documentExpirationDate"
          | "documentIssuerCountry"
          | "documentIssuerState"
          | "documentName"
          | "documentNumber"
          | "documentType"
          | "doingBusinessAs"
          | "drivingLicence"
          | "drivingLicenceBack"
          | "drivingLicenceFront"
          | "drivingLicense"
          | "email"
          | "firstName"
          | "formType"
          | "fullPhoneNumber"
          | "gender"
          | "hopWebserviceUser"
          | "houseNumberOrName"
          | "iban"
          | "idCard"
          | "idCardBack"
          | "idCardFront"
          | "idNumber"
          | "identityDocument"
          | "individualDetails"
          | "infix"
          | "jobTitle"
          | "lastName"
          | "lastReviewDate"
          | "legalArrangement"
          | "legalArrangementCode"
          | "legalArrangementEntity"
          | "legalArrangementEntityCode"
          | "legalArrangementLegalForm"
          | "legalArrangementMember"
          | "legalArrangementMembers"
          | "legalArrangementName"
          | "legalArrangementReference"
          | "legalArrangementRegistrationNumber"
          | "legalArrangementTaxNumber"
          | "legalArrangementType"
          | "legalBusinessName"
          | "legalEntity"
          | "legalEntityType"
          | "logo"
          | "merchantAccount"
          | "merchantCategoryCode"
          | "merchantHouseNumber"
          | "merchantReference"
          | "microDeposit"
          | "name"
          | "nationality"
          | "originalReference"
          | "ownerCity"
          | "ownerCountryCode"
          | "ownerDateOfBirth"
          | "ownerHouseNumberOrName"
          | "ownerName"
          | "ownerPostalCode"
          | "ownerState"
          | "ownerStreet"
          | "passport"
          | "passportNumber"
          | "payoutMethodCode"
          | "payoutSchedule"
          | "pciSelfAssessment"
          | "personalData"
          | "phoneCountryCode"
          | "phoneNumber"
          | "postalCode"
          | "primaryCurrency"
          | "reason"
          | "registrationNumber"
          | "returnUrl"
          | "schedule"
          | "shareholder"
          | "shareholderCode"
          | "shareholderCodeAndSignatoryCode"
          | "shareholderCodeOrSignatoryCode"
          | "shareholderType"
          | "shareholderTypes"
          | "shopperInteraction"
          | "signatory"
          | "signatoryCode"
          | "socialSecurityNumber"
          | "sourceAccountCode"
          | "splitAccount"
          | "splitConfigurationUUID"
          | "splitCurrency"
          | "splitValue"
          | "splits"
          | "stateOrProvince"
          | "status"
          | "stockExchange"
          | "stockNumber"
          | "stockTicker"
          | "store"
          | "storeDetail"
          | "storeName"
          | "storeReference"
          | "street"
          | "taxId"
          | "tier"
          | "tierNumber"
          | "transferCode"
          | "ultimateParentCompany"
          | "ultimateParentCompanyAddressDetails"
          | "ultimateParentCompanyAddressDetailsCountry"
          | "ultimateParentCompanyBusinessDetails"
          | "ultimateParentCompanyBusinessDetailsLegalBusinessName"
          | "ultimateParentCompanyBusinessDetailsRegistrationNumber"
          | "ultimateParentCompanyCode"
          | "ultimateParentCompanyStockExchange"
          | "ultimateParentCompanyStockNumber"
          | "ultimateParentCompanyStockNumberOrStockTicker"
          | "ultimateParentCompanyStockTicker"
          | "unknown"
          | "value"
          | "verificationType"
          | "virtualAccount"
          | "visaNumber"
          | "webAddress"
          | "year";
        /**
         * The code of the shareholder that the field belongs to. If empty, the field belongs to an account holder.
         */
        shareholderCode?: string;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    FieldType: {
      /**
       * The full name of the property.
       */
      field?: string;
      /**
       * The type of the field.
       */
      fieldName?:
        | "accountCode"
        | "accountHolderCode"
        | "accountHolderDetails"
        | "accountNumber"
        | "accountStateType"
        | "accountStatus"
        | "accountType"
        | "address"
        | "balanceAccount"
        | "balanceAccountActive"
        | "balanceAccountCode"
        | "balanceAccountId"
        | "bankAccount"
        | "bankAccountCode"
        | "bankAccountName"
        | "bankAccountUUID"
        | "bankBicSwift"
        | "bankCity"
        | "bankCode"
        | "bankName"
        | "bankStatement"
        | "branchCode"
        | "businessContact"
        | "cardToken"
        | "checkCode"
        | "city"
        | "companyRegistration"
        | "constitutionalDocument"
        | "controller"
        | "country"
        | "countryCode"
        | "currency"
        | "currencyCode"
        | "dateOfBirth"
        | "description"
        | "destinationAccountCode"
        | "document"
        | "documentContent"
        | "documentExpirationDate"
        | "documentIssuerCountry"
        | "documentIssuerState"
        | "documentName"
        | "documentNumber"
        | "documentType"
        | "doingBusinessAs"
        | "drivingLicence"
        | "drivingLicenceBack"
        | "drivingLicenceFront"
        | "drivingLicense"
        | "email"
        | "firstName"
        | "formType"
        | "fullPhoneNumber"
        | "gender"
        | "hopWebserviceUser"
        | "houseNumberOrName"
        | "iban"
        | "idCard"
        | "idCardBack"
        | "idCardFront"
        | "idNumber"
        | "identityDocument"
        | "individualDetails"
        | "infix"
        | "jobTitle"
        | "lastName"
        | "lastReviewDate"
        | "legalArrangement"
        | "legalArrangementCode"
        | "legalArrangementEntity"
        | "legalArrangementEntityCode"
        | "legalArrangementLegalForm"
        | "legalArrangementMember"
        | "legalArrangementMembers"
        | "legalArrangementName"
        | "legalArrangementReference"
        | "legalArrangementRegistrationNumber"
        | "legalArrangementTaxNumber"
        | "legalArrangementType"
        | "legalBusinessName"
        | "legalEntity"
        | "legalEntityType"
        | "logo"
        | "merchantAccount"
        | "merchantCategoryCode"
        | "merchantHouseNumber"
        | "merchantReference"
        | "microDeposit"
        | "name"
        | "nationality"
        | "originalReference"
        | "ownerCity"
        | "ownerCountryCode"
        | "ownerDateOfBirth"
        | "ownerHouseNumberOrName"
        | "ownerName"
        | "ownerPostalCode"
        | "ownerState"
        | "ownerStreet"
        | "passport"
        | "passportNumber"
        | "payoutMethodCode"
        | "payoutSchedule"
        | "pciSelfAssessment"
        | "personalData"
        | "phoneCountryCode"
        | "phoneNumber"
        | "postalCode"
        | "primaryCurrency"
        | "reason"
        | "registrationNumber"
        | "returnUrl"
        | "schedule"
        | "shareholder"
        | "shareholderCode"
        | "shareholderCodeAndSignatoryCode"
        | "shareholderCodeOrSignatoryCode"
        | "shareholderType"
        | "shareholderTypes"
        | "shopperInteraction"
        | "signatory"
        | "signatoryCode"
        | "socialSecurityNumber"
        | "sourceAccountCode"
        | "splitAccount"
        | "splitConfigurationUUID"
        | "splitCurrency"
        | "splitValue"
        | "splits"
        | "stateOrProvince"
        | "status"
        | "stockExchange"
        | "stockNumber"
        | "stockTicker"
        | "store"
        | "storeDetail"
        | "storeName"
        | "storeReference"
        | "street"
        | "taxId"
        | "tier"
        | "tierNumber"
        | "transferCode"
        | "ultimateParentCompany"
        | "ultimateParentCompanyAddressDetails"
        | "ultimateParentCompanyAddressDetailsCountry"
        | "ultimateParentCompanyBusinessDetails"
        | "ultimateParentCompanyBusinessDetailsLegalBusinessName"
        | "ultimateParentCompanyBusinessDetailsRegistrationNumber"
        | "ultimateParentCompanyCode"
        | "ultimateParentCompanyStockExchange"
        | "ultimateParentCompanyStockNumber"
        | "ultimateParentCompanyStockNumberOrStockTicker"
        | "ultimateParentCompanyStockTicker"
        | "unknown"
        | "value"
        | "verificationType"
        | "virtualAccount"
        | "visaNumber"
        | "webAddress"
        | "year";
      /**
       * The code of the shareholder that the field belongs to. If empty, the field belongs to an account holder.
       */
      shareholderCode?: string;
      [k: string]: unknown;
    };
    GetOnboardingUrlRequest: {
      /**
       * The account holder code you provided when you created the account holder.
       */
      accountHolderCode: string;
      collectInformation?: {
        /**
         * Indicates whether [bank account details](https://docs.adyen.com/marketplaces-and-platforms/classic/verification-checks/bank-account-check) must be collected. Default is **true**.
         */
        bankDetails?: boolean;
        /**
         * Indicates whether [business details](https://docs.adyen.com/marketplaces-and-platforms/classic/verification-checks/company-check) must be collected. Default is **true**.
         */
        businessDetails?: boolean;
        /**
         * Indicates whether [individual details](https://docs.adyen.com/marketplaces-and-platforms/classic/verification-checks/identity-check) must be collected. Default is **true**.
         */
        individualDetails?: boolean;
        /**
         * Indicates whether [legal arrangement details](https://docs.adyen.com/marketplaces-and-platforms/classic/verification-checks/legal-arrangements) must be collected. Default is **true**.
         */
        legalArrangementDetails?: boolean;
        /**
         * Indicates whether answers to a [PCI questionnaire](https://docs.adyen.com/marketplaces-and-platforms/classic/platforms-for-partners#onboard-partner-platform) must be collected. Applies only to partner platforms. Default is **true**.
         */
        pciQuestionnaire?: boolean;
        /**
         * Indicates whether [shareholder details](https://docs.adyen.com/marketplaces-and-platforms/classic/verification-checks/identity-check) must be collected. Defaults to **true**.
         */
        shareholderDetails?: boolean;
        [k: string]: unknown;
      };
      /**
       * Indicates if editing checks is allowed even if all the checks have passed.
       */
      editMode?: boolean;
      /**
       * The URL to which the account holder is redirected after completing an OAuth authentication with a bank through Trustly/PayMyBank.
       */
      mobileOAuthCallbackUrl?: string;
      /**
       * The platform name which will show up in the welcome page.
       */
      platformName?: string;
      /**
       * The URL where the account holder will be redirected back to after they complete the onboarding, or if their session times out. Maximum length of 500 characters. If you don't provide this, the account holder will be redirected back to the default return URL configured in your platform account.
       */
      returnUrl?: string;
      /**
       * The language to be used in the page, specified by a combination of a language and country code. For example, **pt-BR**.
       *
       * If not specified in the request or if the language is not supported, the page uses the browser language. If the browser language is not supported, the page uses **en-US** by default.
       *
       * For a list of supported languages, refer to [Change the page language](https://docs.adyen.com/marketplaces-and-platforms/classic/hosted-onboarding-page/customize-experience#change-page-language).
       */
      shopperLocale?: string;
      showPages?: {
        /**
         * Indicates whether the page with bank account details must be shown. Defaults to **true**.
         */
        bankDetailsSummaryPage?: boolean;
        /**
         * Indicates whether the bank check instant verification' details must be shown. Defaults to **true**.
         */
        bankVerificationPage?: boolean;
        /**
         * Indicates whether the page with the company's or organization's details must be shown. Defaults to **true**.
         */
        businessDetailsSummaryPage?: boolean;
        /**
         * Indicates whether the checks overview page must be shown. Defaults to **false**.
         */
        checksOverviewPage?: boolean;
        /**
         * Indicates whether the page with the individual's details must be shown. Defaults to **true**.
         */
        individualDetailsSummaryPage?: boolean;
        /**
         * Indicates whether the page with the legal arrangements' details must be shown. Defaults to **true**.
         */
        legalArrangementsDetailsSummaryPage?: boolean;
        /**
         * Indicates whether the page to manually add bank account' details must be shown. Defaults to **true**.
         */
        manualBankAccountPage?: boolean;
        /**
         * Indicates whether the page with the shareholders' details must be shown. Defaults to **true**.
         */
        shareholderDetailsSummaryPage?: boolean;
        /**
         * Indicates whether the welcome page must be shown. Defaults to **false**.
         */
        welcomePage?: boolean;
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    GetOnboardingUrlResponse: {
      /**
       * Information about any invalid fields.
       */
      invalidFields?: {
        /**
         * The validation error code.
         */
        errorCode?: number;
        /**
         * A description of the validation error.
         */
        errorDescription?: string;
        fieldType?: {
          /**
           * The full name of the property.
           */
          field?: string;
          /**
           * The type of the field.
           */
          fieldName?:
            | "accountCode"
            | "accountHolderCode"
            | "accountHolderDetails"
            | "accountNumber"
            | "accountStateType"
            | "accountStatus"
            | "accountType"
            | "address"
            | "balanceAccount"
            | "balanceAccountActive"
            | "balanceAccountCode"
            | "balanceAccountId"
            | "bankAccount"
            | "bankAccountCode"
            | "bankAccountName"
            | "bankAccountUUID"
            | "bankBicSwift"
            | "bankCity"
            | "bankCode"
            | "bankName"
            | "bankStatement"
            | "branchCode"
            | "businessContact"
            | "cardToken"
            | "checkCode"
            | "city"
            | "companyRegistration"
            | "constitutionalDocument"
            | "controller"
            | "country"
            | "countryCode"
            | "currency"
            | "currencyCode"
            | "dateOfBirth"
            | "description"
            | "destinationAccountCode"
            | "document"
            | "documentContent"
            | "documentExpirationDate"
            | "documentIssuerCountry"
            | "documentIssuerState"
            | "documentName"
            | "documentNumber"
            | "documentType"
            | "doingBusinessAs"
            | "drivingLicence"
            | "drivingLicenceBack"
            | "drivingLicenceFront"
            | "drivingLicense"
            | "email"
            | "firstName"
            | "formType"
            | "fullPhoneNumber"
            | "gender"
            | "hopWebserviceUser"
            | "houseNumberOrName"
            | "iban"
            | "idCard"
            | "idCardBack"
            | "idCardFront"
            | "idNumber"
            | "identityDocument"
            | "individualDetails"
            | "infix"
            | "jobTitle"
            | "lastName"
            | "lastReviewDate"
            | "legalArrangement"
            | "legalArrangementCode"
            | "legalArrangementEntity"
            | "legalArrangementEntityCode"
            | "legalArrangementLegalForm"
            | "legalArrangementMember"
            | "legalArrangementMembers"
            | "legalArrangementName"
            | "legalArrangementReference"
            | "legalArrangementRegistrationNumber"
            | "legalArrangementTaxNumber"
            | "legalArrangementType"
            | "legalBusinessName"
            | "legalEntity"
            | "legalEntityType"
            | "logo"
            | "merchantAccount"
            | "merchantCategoryCode"
            | "merchantHouseNumber"
            | "merchantReference"
            | "microDeposit"
            | "name"
            | "nationality"
            | "originalReference"
            | "ownerCity"
            | "ownerCountryCode"
            | "ownerDateOfBirth"
            | "ownerHouseNumberOrName"
            | "ownerName"
            | "ownerPostalCode"
            | "ownerState"
            | "ownerStreet"
            | "passport"
            | "passportNumber"
            | "payoutMethodCode"
            | "payoutSchedule"
            | "pciSelfAssessment"
            | "personalData"
            | "phoneCountryCode"
            | "phoneNumber"
            | "postalCode"
            | "primaryCurrency"
            | "reason"
            | "registrationNumber"
            | "returnUrl"
            | "schedule"
            | "shareholder"
            | "shareholderCode"
            | "shareholderCodeAndSignatoryCode"
            | "shareholderCodeOrSignatoryCode"
            | "shareholderType"
            | "shareholderTypes"
            | "shopperInteraction"
            | "signatory"
            | "signatoryCode"
            | "socialSecurityNumber"
            | "sourceAccountCode"
            | "splitAccount"
            | "splitConfigurationUUID"
            | "splitCurrency"
            | "splitValue"
            | "splits"
            | "stateOrProvince"
            | "status"
            | "stockExchange"
            | "stockNumber"
            | "stockTicker"
            | "store"
            | "storeDetail"
            | "storeName"
            | "storeReference"
            | "street"
            | "taxId"
            | "tier"
            | "tierNumber"
            | "transferCode"
            | "ultimateParentCompany"
            | "ultimateParentCompanyAddressDetails"
            | "ultimateParentCompanyAddressDetailsCountry"
            | "ultimateParentCompanyBusinessDetails"
            | "ultimateParentCompanyBusinessDetailsLegalBusinessName"
            | "ultimateParentCompanyBusinessDetailsRegistrationNumber"
            | "ultimateParentCompanyCode"
            | "ultimateParentCompanyStockExchange"
            | "ultimateParentCompanyStockNumber"
            | "ultimateParentCompanyStockNumberOrStockTicker"
            | "ultimateParentCompanyStockTicker"
            | "unknown"
            | "value"
            | "verificationType"
            | "virtualAccount"
            | "visaNumber"
            | "webAddress"
            | "year";
          /**
           * The code of the shareholder that the field belongs to. If empty, the field belongs to an account holder.
           */
          shareholderCode?: string;
          [k: string]: unknown;
        };
        [k: string]: unknown;
      }[];
      /**
       * The reference of a request. Can be used to uniquely identify the request.
       */
      pspReference?: string;
      /**
       * The URL to the Hosted Onboarding Page where you should redirect your sub-merchant. This URL must be used within 30 seconds and can only be used once.
       */
      redirectUrl?: string;
      /**
       * The result code.
       */
      resultCode?: string;
      [k: string]: unknown;
    };
    GetPciUrlRequest: {
      /**
       * The account holder code you provided when you created the account holder.
       */
      accountHolderCode: string;
      /**
       * The URL where the account holder will be redirected back to after they fill out the questionnaire, or if their session times out. Maximum length of 500 characters.
       */
      returnUrl?: string;
      [k: string]: unknown;
    };
    GetPciUrlResponse: {
      /**
       * Information about any invalid fields.
       */
      invalidFields?: {
        /**
         * The validation error code.
         */
        errorCode?: number;
        /**
         * A description of the validation error.
         */
        errorDescription?: string;
        fieldType?: {
          /**
           * The full name of the property.
           */
          field?: string;
          /**
           * The type of the field.
           */
          fieldName?:
            | "accountCode"
            | "accountHolderCode"
            | "accountHolderDetails"
            | "accountNumber"
            | "accountStateType"
            | "accountStatus"
            | "accountType"
            | "address"
            | "balanceAccount"
            | "balanceAccountActive"
            | "balanceAccountCode"
            | "balanceAccountId"
            | "bankAccount"
            | "bankAccountCode"
            | "bankAccountName"
            | "bankAccountUUID"
            | "bankBicSwift"
            | "bankCity"
            | "bankCode"
            | "bankName"
            | "bankStatement"
            | "branchCode"
            | "businessContact"
            | "cardToken"
            | "checkCode"
            | "city"
            | "companyRegistration"
            | "constitutionalDocument"
            | "controller"
            | "country"
            | "countryCode"
            | "currency"
            | "currencyCode"
            | "dateOfBirth"
            | "description"
            | "destinationAccountCode"
            | "document"
            | "documentContent"
            | "documentExpirationDate"
            | "documentIssuerCountry"
            | "documentIssuerState"
            | "documentName"
            | "documentNumber"
            | "documentType"
            | "doingBusinessAs"
            | "drivingLicence"
            | "drivingLicenceBack"
            | "drivingLicenceFront"
            | "drivingLicense"
            | "email"
            | "firstName"
            | "formType"
            | "fullPhoneNumber"
            | "gender"
            | "hopWebserviceUser"
            | "houseNumberOrName"
            | "iban"
            | "idCard"
            | "idCardBack"
            | "idCardFront"
            | "idNumber"
            | "identityDocument"
            | "individualDetails"
            | "infix"
            | "jobTitle"
            | "lastName"
            | "lastReviewDate"
            | "legalArrangement"
            | "legalArrangementCode"
            | "legalArrangementEntity"
            | "legalArrangementEntityCode"
            | "legalArrangementLegalForm"
            | "legalArrangementMember"
            | "legalArrangementMembers"
            | "legalArrangementName"
            | "legalArrangementReference"
            | "legalArrangementRegistrationNumber"
            | "legalArrangementTaxNumber"
            | "legalArrangementType"
            | "legalBusinessName"
            | "legalEntity"
            | "legalEntityType"
            | "logo"
            | "merchantAccount"
            | "merchantCategoryCode"
            | "merchantHouseNumber"
            | "merchantReference"
            | "microDeposit"
            | "name"
            | "nationality"
            | "originalReference"
            | "ownerCity"
            | "ownerCountryCode"
            | "ownerDateOfBirth"
            | "ownerHouseNumberOrName"
            | "ownerName"
            | "ownerPostalCode"
            | "ownerState"
            | "ownerStreet"
            | "passport"
            | "passportNumber"
            | "payoutMethodCode"
            | "payoutSchedule"
            | "pciSelfAssessment"
            | "personalData"
            | "phoneCountryCode"
            | "phoneNumber"
            | "postalCode"
            | "primaryCurrency"
            | "reason"
            | "registrationNumber"
            | "returnUrl"
            | "schedule"
            | "shareholder"
            | "shareholderCode"
            | "shareholderCodeAndSignatoryCode"
            | "shareholderCodeOrSignatoryCode"
            | "shareholderType"
            | "shareholderTypes"
            | "shopperInteraction"
            | "signatory"
            | "signatoryCode"
            | "socialSecurityNumber"
            | "sourceAccountCode"
            | "splitAccount"
            | "splitConfigurationUUID"
            | "splitCurrency"
            | "splitValue"
            | "splits"
            | "stateOrProvince"
            | "status"
            | "stockExchange"
            | "stockNumber"
            | "stockTicker"
            | "store"
            | "storeDetail"
            | "storeName"
            | "storeReference"
            | "street"
            | "taxId"
            | "tier"
            | "tierNumber"
            | "transferCode"
            | "ultimateParentCompany"
            | "ultimateParentCompanyAddressDetails"
            | "ultimateParentCompanyAddressDetailsCountry"
            | "ultimateParentCompanyBusinessDetails"
            | "ultimateParentCompanyBusinessDetailsLegalBusinessName"
            | "ultimateParentCompanyBusinessDetailsRegistrationNumber"
            | "ultimateParentCompanyCode"
            | "ultimateParentCompanyStockExchange"
            | "ultimateParentCompanyStockNumber"
            | "ultimateParentCompanyStockNumberOrStockTicker"
            | "ultimateParentCompanyStockTicker"
            | "unknown"
            | "value"
            | "verificationType"
            | "virtualAccount"
            | "visaNumber"
            | "webAddress"
            | "year";
          /**
           * The code of the shareholder that the field belongs to. If empty, the field belongs to an account holder.
           */
          shareholderCode?: string;
          [k: string]: unknown;
        };
        [k: string]: unknown;
      }[];
      /**
       * The reference of a request. Can be used to uniquely identify the request.
       */
      pspReference?: string;
      /**
       * The URL to the PCI compliance questionnaire where you should redirect your account holder. This URL must be used within 30 seconds and can only be used once.
       */
      redirectUrl?: string;
      /**
       * The result code.
       */
      resultCode?: string;
      [k: string]: unknown;
    };
    ServiceError: {
      /**
       * The error code mapped to the error message.
       */
      errorCode?: string;
      /**
       * The category of the error.
       */
      errorType?: string;
      /**
       * A short explanation of the issue.
       */
      message?: string;
      /**
       * The PSP reference of the payment.
       */
      pspReference?: string;
      /**
       * The HTTP response status.
       */
      status?: number;
      [k: string]: unknown;
    };
    ShowPages: {
      /**
       * Indicates whether the page with bank account details must be shown. Defaults to **true**.
       */
      bankDetailsSummaryPage?: boolean;
      /**
       * Indicates whether the bank check instant verification' details must be shown. Defaults to **true**.
       */
      bankVerificationPage?: boolean;
      /**
       * Indicates whether the page with the company's or organization's details must be shown. Defaults to **true**.
       */
      businessDetailsSummaryPage?: boolean;
      /**
       * Indicates whether the checks overview page must be shown. Defaults to **false**.
       */
      checksOverviewPage?: boolean;
      /**
       * Indicates whether the page with the individual's details must be shown. Defaults to **true**.
       */
      individualDetailsSummaryPage?: boolean;
      /**
       * Indicates whether the page with the legal arrangements' details must be shown. Defaults to **true**.
       */
      legalArrangementsDetailsSummaryPage?: boolean;
      /**
       * Indicates whether the page to manually add bank account' details must be shown. Defaults to **true**.
       */
      manualBankAccountPage?: boolean;
      /**
       * Indicates whether the page with the shareholders' details must be shown. Defaults to **true**.
       */
      shareholderDetailsSummaryPage?: boolean;
      /**
       * Indicates whether the welcome page must be shown. Defaults to **false**.
       */
      welcomePage?: boolean;
      [k: string]: unknown;
    };
  };
}
